### ISSUE TITLE
Homekit Light Temperature

### ISSUE THREAD

**Issue by intdel** [fsaris/home-assistant-awox#37]
I added my lights to home assistant and combined it with the homekit integration. However, through the homekit app on my iPhone I can only set colors. I am not able to change it to "white (bright) mode" with the different temperatures.

Any ideas?

**Comment by fsaris** [comment]
Please enable debug logging (https://github.com/fsaris/home-assistant-awox#troubleshooting) and check the logs for ` Turn on ...` lines. I'm curious what info that shows, maybe it gives a clue what we are missing in the integration for this to work.

**Comment by vdebrist** [comment]
The same problem. Also, MESH not works. I can manage only bulbs, which are close to the Raspberry. From the AWOX app I can manage all bulbs (inlc. blulbs are out of direct BT range of the phone). Maybe you can fix it. @fsaris Your work is awesome! Because of your integration I have changed HomeBridge to Home Assistant.

**Comment by fsaris** [comment]
Light temperature is adjusted in current main version.

@vdebrist the integration only uses mesh to control the lights. Are you sure the lights are in range of each other?
