### ISSUE TITLE
Awox plug plus integration would allow wifi acces : requested

### ISSUE THREAD

**Issue by MarcW-HA** [fsaris/home-assistant-awox#48]
Hello,
If I may suggest to put the Awox connect plug plus on your highest priority followed by the adoption of the same rooms as in the Awox app would open a world of possibilities.
The plug is a wifi bridge via the awox cloud it sees all the bleutooth devices in its mesch.
Intégration allows thus to use the lights without bleutooth in the range of the HA server. This would be a blessing for those who can not reach a bleutooth device from the HA server.
Note for info remote control and pir detection work in bleutooth range even if the HA server has taken the bleutooth mesch in control of the lamps.
I have the plug so willing to test. 

Good work just needs some work to make it super great
Thx

**Comment by fsaris** [comment]
If you sponsor my such a plug I will definitely dive into it. But currently I don't have such a device

**Comment by MarcW-HA** [comment]
Hello,If you agree to send me your address I will figure out what is the most appropriate. I send you one by mail, here I have one for 39.95euro. Or I can send you the funds transfer then I will need the Iban and rib of your bank account. PS : I live in Luxembourg. Just let me knowMarcEnvoyé depuis mon téléphone Huawei-------- Message original --------De : Frans Saris ***@***.***>Date : mar. 3 août 2021 à 19:36À : fsaris/home-assistant-awox ***@***.***>Cc : MarcW-HA ***@***.***>, Author ***@***.***>Objet : Re: [fsaris/home-assistant-awox] Awox plug plus integration would allow wifi acces : requested (#48)
If you sponsor my such a plug I will definitely dive into it. But currently I don't have such a device

**Comment by fsaris** [comment]
Please contact me at franssaris@gmail.com

**Comment by Dillton** [comment]
Hello guys.

I got recently the EGLO lights and theyre all connected to HA without problem. But the problem maybe lets say 2 problems are I think in my bluetooth adapter. I am running windows PC with installed HA in virtualbox. So first problem I had issue with range of BT signal - solved with 5dbi antenna connected to BT module in PC. However second issue persists. After some time of HA is running I dont know why but for some reason all lights not responding to HA commands (on/off, etc.). I think that might be because of ZigBee module which causes some signal interference?

And there are my questions:
1) Are you able to somehow help me with debugging? Some remote session or sent you logs or something like that please :)?
    I am completely opened to provide any data so the integration will be 110% functional :).
2) What is the status of implementing the EGLO Plug + to the integration? I think this will solve both of my problems.

Anyway thank you very much and great job with Awox integration I really appreciate it, keep up.

**Comment by Dillton** [comment]
Maybe I have one more idea. I am using in my living room and in bedroom Raspberry PIs with touchscreen as HA control panels for those rooms. So maybe create some plugin for RPIs and use their built-in bluetooth to be a part of Awox mesh?

**Comment by fsaris** [comment]
looks like the bluetooth adapter isn't very stable. Is it near enough of the light?

**Comment by fsaris** [comment]
Will dive into that in one of the next days. Integration should try to reconnect in this case.

But also looks that your Bluetooth adapter isn't that stable.

**Comment by Dillton** [comment]
Hello @fsaris,
so I have tried another BT adapter and still the same errors.
Do you have any progress with the integration? :)

**Comment by fsaris** [comment]
Improved logging and connecting process was added in https://github.com/fsaris/home-assistant-awox/releases/tag/0.1.2

Closing this ticket now as the basic support for plugs is available. For now the wifi is out of scope. Not sure even if it would be possible to use the wifi without using the Awox webservices.
