### ISSUE TITLE
Getting only timed out

### ISSUE THREAD

**Issue by d0girankaisee** [fsaris/home-assistant-awox#84]
My mesh was working, but not anymore. Only getting "timed out" error messages, and awox mesh stays not available state. Any solutions? Tried re-install awox and Bluetooth, these not helping. 
![image](https://user-images.githubusercontent.com/115560901/212660851-b1f9b5ca-27c7-4b33-94c2-5ff618e11a22.png)

**Comment by fsaris** [comment]
Please try to revert to previous version for now

**Comment by d0girankaisee** [comment]
> Please try to revert to previous version for now

Not helping :/

**Comment by fsaris** [comment]
The integration needs a dedicated Bluetooth controller because it doesn't work with bleak/bluez. I noticed that the Bluetooth integration in HA gives me some issues regarding this. I tried disabling it etc but all kept giving issues again after HA updates.
I'm now focusing on a ESPHome solution https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub the Bluetooth connection looks more stable.

**Comment by fsaris** [comment]
Please open a new Q&A discussion if you need more support
